---
title: "initial cleaning"
output: html_document
date: "2023-11-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(haven)
library(janitor)
library(knitr)
library(surveytoolbox)
library(sjPlot)
library(kableExtra)
library(psych)
library(sjmisc)

theme_set(theme_minimal())
```

# Loading the dataset (cohort 1)
```{r}
d_raw_c1 <- import(here("nopublish", "1MdMMedicinCUIDADORE_DATA_2023-11-16_1846_cohort1.csv"), setclass = "tbl_df")
```

#initial cleaning (cohort 1)
```{r}

# d_raw_c1 <- d_raw_c1[-c(1:5), ] # to remove rows of data

d_c1 <- d_raw_c1 %>% 
  select(-2:-7, -11:-13, -203:-210) %>% # selecting out columns with non-relevant data (, -238:-255)
  clean_names() %>% # function that formats variables' names
  # arrange(record_id) # ordering participants ids in descending order (not doing this because record_id needs further cleaning)
```

Need to find a way to add the condition of the study:

odd record_id = 1 = intervention
even record_id = 2 = control


```{r}
test <- d_c1 %>%
  mutate(condition_in_the_study = case_when(
    record_id >= "0201" & record_id <= "0299" |  ~ "2",
    TRUE ~ as.character(condition_in_the_study))) # this works, but when I add the other conditions it breaks. 

```

# before (cohort 1)
```{r}
# view_df(d_c1)
```

# renaming variables (cohort 1)
```{r}
d1_c1 <- d_c1 %>% 
  rename(c("new_name" = "old_name")) %>% # to match coh_
  rename(c("new_name" = "old_name")) %>% # to match coh_
  rename(c("new_name" = "old_name")) %>% # to match coh_
  
  
  # rename(c("demo014_1_77" = "demo014_1_5")) %>% # to match coh_2
  # rename(c("demo019_1_77" = "demo019_1_10")) %>% # to match coh_2
```


# Adding Variable and value labels
```{r}
# d3 <- d2 %>%
#   mutate(sdq001_1 = as.numeric(sdq001_1),
#          sdq001_1 = set_varl(sdq001_1, "Tiene en cuenta los sentimientos de otras personas"),
#          sdq001_1 = set_vall(sdq001_1, c("No es cierto" = 0, "Algo cierto" = 1, "Totalmente cierto" = 2, "No responde" = 99))) # puede escribirse en ingles
```


# recoding missing variables as N/A
```{r include=FALSE}

# vector with missing values in dataset
missing_vals <- c(77, 99)

# function that returns true if values in vector are equal to missing_vals. The function takes a vector x, and specified values of missing data
recode_missing <- function(x, missing_vals = c(77, 99)) {
  test <- x %in% missing_vals
  ifelse(test, NA, x)
}

# function that recodes missing values to NA. The function takes a dataframe with variables with missing data, and specified values of missing data
recode_missing_df <- function(df, missing_vals = c(77, 99)) {
  modify(df, ~recode_missing(.x, missing_vals)) # here uses the function created above
}

d2_c1 <- recode_missing_df(d1_c1) # the function strips out variable labels
```


# after (cohort 1)
```{r}
# view_df(d2_c1)
```

# descriptive stats function
```{r include=FALSE}

# function that takes a df and returns a df with only the numeric columns
only_numeric <- function(df) {
  select_numeric <- dplyr::select_if(df, is.numeric)
  return(select_numeric)
}

# a list with the functions we want
smry <- list(n = function(x) length(x),
             n_valid = function(x) sum(!is.na(x)),
             na = function(x) sum(is.na(x)),
             M = function(x) round(mean(x, na.rm = TRUE), 2), 
             SD = function(x) round(sd(x, na.rm = TRUE), 2),
             Min = function(x) round(min(x, na.rm = TRUE), 2),
             Max = function(x) round(max(x, na.rm = TRUE), 2))

# wrapping solution in a function
descriptives <- function(df) {
  select_numeric <- only_numeric(df)
  mean_sd <- map_df(select_numeric, function(col) map_df(smry, ~.x(col)),
       .id = "column")
  return(mean_sd)
}
```


-----

# Loading the dataset cohort 2
```{r}
d_raw_c2 <- import(here("nopublish", "1MdMMedicinCUIDADORE_DATA_2023-11-16_1842_cohort2.csv"), setclass = "tbl_df")
```

# renaming variables (cohort 2)
```{r}

# d1_c2 <- d_c2 %>% 
#   rename(c("demo014_1_5" = "demo014_1_77")) %>% # to match coh_1
#   rename(c("demo019_1_10" = "demo019_1_77")) %>% # to match coh_1
```
