---
title: "MdM parent scales"
author: "Alejandra Garcia Isaza"
date: "2025-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(haven)
library(janitor)
library(knitr)
library(surveytoolbox)
library(sjPlot)
library(kableExtra)
library(psych)
library(sjmisc)

theme_set(theme_minimal())
```


### Loading the dataset (cohort 1 and 2 - wave 1)
```{r}
d <- import(here("data", "caregivers_co1_co2_w1.sav"), setclass = "tbl_df")

view_df(d) # Not showing each value label separate. Values appear as range, prob due to haven stripping labels when I exported. 
```


### recoding missing variables as N/A
```{r include=FALSE}

# vector with missing values in dataset
missing_vals <- c(77, 99)

# function that returns true if values in vector are equal to missing_vals. The function takes a vector x, and specified values of missing data
recode_missing <- function(x, missing_vals = c(77, 99)) {
  test <- x %in% missing_vals
  ifelse(test, NA, x)
}

# function that recodes missing values to NA. The function takes a dataframe with variables with missing data, and specified values of missing data
recode_missing_df <- function(df, missing_vals = c(77, 99)) {
  modify(df, ~recode_missing(.x, missing_vals)) # here uses the function created above
}

d1 <- recode_missing_df(d) # the function strips out variable labels
```


demo001_1:
1, Femenino = 1057
2, Masculino = 163
99/NA, Prefiero no responder	= 5 
total = 1225

Conclusions of my sleuthing: 
female caregivers = 1060
male caregivers = 164
1 row with na, id 2542 (?)
total = 1225

```{r}
# age
mean(d1$demo002_1, na.rm = TRUE)
sd(d1$demo002_1, na.rm = TRUE)

# gender
d1 %>%
  	count(demo001_1)

# to identify who is the na
d1 %>% filter(is.na(demo001_1))

# Sleuthing:
d1 %>% filter(record_id == "438") # madre -- lots of prefer not to respond
d1 %>% filter(record_id == "835") # tia
d1 %>% filter(record_id == "2122") # padre
d1 %>% filter(record_id == "2542") # na -- lots of prefer not to respond
d1 %>% filter(record_id == "2824") # madre

# affiliation with child
d1 %>%
  count(intro001_1) %>%
  mutate(percent = n / sum(n) * 100)
#cat(paste(d1$intro001input_a_1, collapse = "\n"))

# Ed level
d1 %>%
  count(demo004_1) %>%
  mutate(percent = n / sum(n) * 100)

#have a job
d1 %>%
  count(demo005_1) %>%
  mutate(percent = n / sum(n) * 100)

# hours of work
d1 %>%
  filter(demo005input_b_1 == "0")
# id 2330 has a value of 8000, which I am excluding
# id 1509	has a value of 0, bec she is retired

mean(d1$demo005input_b_1[!d1$demo005input_b_1 %in% c(0, 8000)], na.rm = TRUE)
sd(d1$demo005input_b_1[!d1$demo005input_b_1 %in% c(0, 8000)], na.rm = TRUE)
range(d1$demo005input_b_1[!d1$demo005input_b_1 %in% c(0, 8000)], na.rm = TRUE)

# income enough?
d1 %>%
  count(demo007_1) %>%
  mutate(percent = n / sum(n) * 100)

# food insecurity
d1 %>%
  count(demo008_1) %>%
  mutate(percent = n / sum(n) * 100)

# previous caregiver now abroad
d1 %>%
  count(demo018_1) %>%
  mutate(percent = n / sum(n) * 100) # ~10%

# hours per day w/child on a weekday
d1 %>%
  count(demo023_1) %>%
  mutate(percent = n / sum(n) * 100)

# estado civil
d1 %>%
  count(demo003_1) %>%
  mutate(percent = n / sum(n) * 100)

# primary caregiver
d1 %>%
  count(demo021_1) %>%
  mutate(percent = n / sum(n) * 100)
```


```{r}
# Step 1: Recode values with labels
dw1 <- d1 %>%
  mutate(demo007_1_label = case_when(
    demo007_1 == 1 ~ "Yes, and we can save from it",
    demo007_1 == 2 ~ "Yes, just enough",
    demo007_1 == 3 ~ "No, we are stretched",
    demo007_1 == 4 ~ "No, we are struggling",
    TRUE ~ "Missing/Other"
  ))

# Step 2: Count and calculate percentages
demo_counts <- dw1 %>%
  count(demo007_1_label) %>%
  mutate(percent = round(100 * n / sum(n), 1),
         label = paste0(demo007_1_label, " (", percent, "%)"))

# Step 3: Create pie chart with percentages
ggplot(demo_counts, aes(x = "", y = n, fill = demo007_1_label)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(percent, "%")),
            position = position_stack(vjust = 0.5),
            color = "white", size = 4.5) +
  theme_void() +
  labs(title = "Is Family Income Enough?",
       fill = "Income") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.title = element_text(face = "bold"))
```





### Data prep: reverse scoring negatively worded items

SDQ values = 0, 1, 2
PAFAS values = 0, 1, 2, 3
```{r}
d2 <- d1 %>%
  mutate(sdq007_1 = likert_reverse(sdq007_1, top = 2, bottom = 0),
         sdq021_1 = likert_reverse(sdq021_1, top = 2, bottom = 0),
         sdq025_1 = likert_reverse(sdq025_1, top = 2, bottom = 0),
         sdq011_1 = likert_reverse(sdq011_1, top = 2, bottom = 0),
         sdq014_1 = likert_reverse(sdq014_1, top = 2, bottom = 0),
         pafas003_1 = likert_reverse(pafas003_1, top = 3, bottom = 0),
         pafas011_1 = likert_reverse(pafas011_1, top = 3, bottom = 0),
         pafas019_1 = likert_reverse(pafas019_1, top = 3, bottom = 0),
         pafas020_1 = likert_reverse(pafas020_1, top = 3, bottom = 0),
         couple001_2 = likert_reverse(couple001_2, top = 3, bottom = 0),
         )
```


### checking reverse scoring
```{r}
# d1$sdq007_1
# d2$sdq007_1
# Conclusion: it worked

# d1$pafas019_1
# d2$pafas019_1
# Conclusion: it worked
```
